### ISSUE TITLE
0.30 no longer shows timestamps/node status

### ISSUE THREAD

**Issue by gregg098** [AYapejian/node-red-contrib-home-assistant#53]
I just recently updated to the 0.30 node and while it has a lot of great additions, one thing I miss are timestamps when events were triggered. I used to check timestamps in the flows (without debug nodes) periodically to see if they appeared to be working correctly. Can you add this if time permits? Low priority suggestion.

**Comment by oakbrad** [comment]
I also miss this, some other nodes seem to have retained some of their timestamps. Any ways to bring them back for HA?

**Comment by nphil** [comment]
yes, please add this back! It was very useful.

**Comment by oakbrad** [comment]
Looks like pull request #66 brings this back, just awaiting approval from dev.

**Comment by Spartan-II-117** [comment]
it starts to, I have a more complete version in my repo, but i don't want to put a ton of work into it if the dev wants it done differently.

**Comment by x99percent** [comment]
Spartan, I got it working from your code, but there were errors in api_current-state.js, poll-state.js, and server-events-state-changed.js.

**Comment by Spartan-II-117** [comment]
@x99percent yeah, i'm still working on it, feel free to submit patches! I think i fixed api-current-state as well as server-events-state-changed, I haven't touched poll-state again yet

**Comment by bwoodworth** [comment]
Any update on this?  I am running 0.5.0 on hassio (Frenck addon) and still don't get node statuses.

**Comment by Spartan-II-117** [comment]
This branch is dead, you can use my fork (note, I'm not much of a programmer, but i got statuses to work and the whole thing SHOULD now be backwards compatible with this one)

**Comment by bwoodworth** [comment]
How do I use your fork?  I just install Frenck's add on and the hass pallet was already installed

**Comment by Spartan-II-117** [comment]
https://community.home-assistant.io/t/community-hass-io-add-on-node-red/55023/64

**Comment by Spartan-II-117** [comment]
you'll want to change the pined version to the current version

**Comment by bwoodworth** [comment]
I tried changing the version to 0.3.5 and it fails:

[cont-init.d] 81-npm-packages.sh: executing... 
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout v0.3.5
npm ERR! error: pathspec 'v0.3.5' did not match any file(s) known to git.
npm ERR! 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-03T19_30_07_495Z-debug.log
FATAL: Failed installing npm package git+https://github.com/Spartan-II-117/node-red-contrib-home-assistant#v0.3.5

**Comment by Spartan-II-117** [comment]
remove the v, it's just 0.3.5
